kind: Pod
apiVersion: v1
metadata:
  name: podwithnodeselector
spec:
  nodeSelector: 
    ram: high
  containers:
  - name: container-1
    image: usama9876/first-docker-app
    ports: 
    -  containerPort: 80

