kind: Pod
apiVersion: v1
metadata:
  name: podwithlabels
  labels: 
    type: frontend
    env: production
spec:
  containers:
  - name: container-1
    image: usama9876/first-docker-app
    ports: 
    -  containerPort: 80

